- hosts: localhost
  vars:
    source_key: "./.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
  vars:
    source_key: "./.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
  pre_tasks:
    - name: Update Apt
      become: true
      apt:
        force_apt_get: true
        update_cache: true
        state: present
      tags:
        - install
        - core
  tasks:
    - include: tasks/git-setup.yml
    - include: tasks/core.yml
    - include: tasks/brave.yml
    - include: tasks/dotfiles.yml
    - include: tasks/node.yml
    - include: tasks/npm-packages.yml
    - include: tasks/nvim.yml
    - include: tasks/rustup.yml
    - include: tasks/zsh.yml
    - include: tasks/alacritty.yml
    - include: tasks/productivity-tools.yml
    - include: tasks/rustup.yml
    - include: tasks/wezterm.yml
