- name: Installing stow
  apt: name=stow
  tags:
    - install
    - dotfiles
    - stow
- name: Cloning .dotfiles
  ansible.builtin.git:
    repo: "https://github.com/bduckdev/.dotfiles"
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: main
  tags:
    - install
    - dotfiles
    - stow
- name: Stow dotfiles
  shell: cd ~/.dotfiles && stow */
  tags:
    - install
    - dotfiles
    - stow
